# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fe3_panel.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 824)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.layout_left = QtWidgets.QVBoxLayout()
        self.layout_left.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_left.setContentsMargins(-1, -1, 0, -1)
        self.layout_left.setObjectName("layout_left")
        self.runselction_box = QtWidgets.QGroupBox(self.tab)
        self.runselction_box.setStyleSheet("QGroupBox {\n"
"background-color: rgb(223, 248, 250) ;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: left top;\n"
"    background: transparent;\n"
"}")
        self.runselction_box.setObjectName("runselction_box")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.runselction_box)
        self.verticalLayout_7.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.layout_runselect = QtWidgets.QVBoxLayout()
        self.layout_runselect.setObjectName("layout_runselect")
        self.box_runs = QtWidgets.QComboBox(self.runselction_box)
        self.box_runs.setObjectName("box_runs")
        self.layout_runselect.addWidget(self.box_runs)
        self.label_runtype = QtWidgets.QLabel(self.runselction_box)
        self.label_runtype.setObjectName("label_runtype")
        self.layout_runselect.addWidget(self.label_runtype)
        self.box_types = QtWidgets.QComboBox(self.runselction_box)
        self.box_types.setObjectName("box_types")
        self.layout_runselect.addWidget(self.box_types)
        self.label_rundate = QtWidgets.QLabel(self.runselction_box)
        self.label_rundate.setObjectName("label_rundate")
        self.layout_runselect.addWidget(self.label_rundate)
        self.box_dates = QtWidgets.QComboBox(self.runselction_box)
        self.box_dates.setObjectName("box_dates")
        self.layout_runselect.addWidget(self.box_dates)
        self.verticalLayout_7.addLayout(self.layout_runselect)
        self.layout_left.addWidget(self.runselction_box, 0, QtCore.Qt.AlignTop)
        self.gases_box = QtWidgets.QGroupBox(self.tab)
        self.gases_box.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(255, 253, 231);\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: left top;\n"
"    background: transparent;\n"
"}")
        self.gases_box.setObjectName("gases_box")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.gases_box)
        self.verticalLayout_9.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.layout_gasbuttons = QtWidgets.QGridLayout()
        self.layout_gasbuttons.setVerticalSpacing(10)
        self.layout_gasbuttons.setObjectName("layout_gasbuttons")
        self.button_CFC12 = QtWidgets.QRadioButton(self.gases_box)
        self.button_CFC12.setObjectName("button_CFC12")
        self.buttonGroup_mols1 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_mols1.setObjectName("buttonGroup_mols1")
        self.buttonGroup_mols1.addButton(self.button_CFC12)
        self.layout_gasbuttons.addWidget(self.button_CFC12, 2, 1, 1, 1)
        self.button_CFC113 = QtWidgets.QRadioButton(self.gases_box)
        self.button_CFC113.setObjectName("button_CFC113")
        self.buttonGroup_mols1.addButton(self.button_CFC113)
        self.layout_gasbuttons.addWidget(self.button_CFC113, 1, 0, 1, 1)
        self.button_TCE = QtWidgets.QRadioButton(self.gases_box)
        self.button_TCE.setObjectName("button_TCE")
        self.buttonGroup_mols1.addButton(self.button_TCE)
        self.layout_gasbuttons.addWidget(self.button_TCE, 5, 0, 1, 1)
        self.button_SF6 = QtWidgets.QRadioButton(self.gases_box)
        self.button_SF6.setObjectName("button_SF6")
        self.buttonGroup_mols1.addButton(self.button_SF6)
        self.layout_gasbuttons.addWidget(self.button_SF6, 1, 1, 1, 1)
        self.button_N2O = QtWidgets.QRadioButton(self.gases_box)
        self.button_N2O.setObjectName("button_N2O")
        self.buttonGroup_mols1.addButton(self.button_N2O)
        self.layout_gasbuttons.addWidget(self.button_N2O, 0, 1, 1, 1)
        self.button_CHCl3 = QtWidgets.QRadioButton(self.gases_box)
        self.button_CHCl3.setObjectName("button_CHCl3")
        self.buttonGroup_mols1.addButton(self.button_CHCl3)
        self.layout_gasbuttons.addWidget(self.button_CHCl3, 2, 0, 1, 1)
        self.button_CFC11 = QtWidgets.QRadioButton(self.gases_box)
        self.button_CFC11.setEnabled(True)
        self.button_CFC11.setObjectName("button_CFC11")
        self.buttonGroup_mols1.addButton(self.button_CFC11)
        self.layout_gasbuttons.addWidget(self.button_CFC11, 0, 0, 1, 1)
        self.button_CCl4 = QtWidgets.QRadioButton(self.gases_box)
        self.button_CCl4.setObjectName("button_CCl4")
        self.buttonGroup_mols1.addButton(self.button_CCl4)
        self.layout_gasbuttons.addWidget(self.button_CCl4, 4, 0, 1, 1)
        self.button_MC = QtWidgets.QRadioButton(self.gases_box)
        self.button_MC.setObjectName("button_MC")
        self.buttonGroup_mols1.addButton(self.button_MC)
        self.layout_gasbuttons.addWidget(self.button_MC, 3, 0, 1, 1)
        self.button_h1211 = QtWidgets.QRadioButton(self.gases_box)
        self.button_h1211.setObjectName("button_h1211")
        self.buttonGroup_mols1.addButton(self.button_h1211)
        self.layout_gasbuttons.addWidget(self.button_h1211, 3, 1, 1, 1)
        self.button_CFC11b = QtWidgets.QRadioButton(self.gases_box)
        self.button_CFC11b.setObjectName("button_CFC11b")
        self.buttonGroup_mols1.addButton(self.button_CFC11b)
        self.layout_gasbuttons.addWidget(self.button_CFC11b, 4, 1, 1, 1)
        self.button_CFC113b = QtWidgets.QRadioButton(self.gases_box)
        self.button_CFC113b.setObjectName("button_CFC113b")
        self.buttonGroup_mols1.addButton(self.button_CFC113b)
        self.layout_gasbuttons.addWidget(self.button_CFC113b, 5, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.layout_gasbuttons)
        self.layout_left.addWidget(self.gases_box, 0, QtCore.Qt.AlignTop)
        self.figures_box = QtWidgets.QGroupBox(self.tab)
        self.figures_box.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(212, 255, 223)\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: left top;\n"
"    background: transparent;\n"
"}")
        self.figures_box.setObjectName("figures_box")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.figures_box)
        self.verticalLayout_10.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.fig_response = QtWidgets.QRadioButton(self.figures_box)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fig_response.setFont(font)
        self.fig_response.setObjectName("fig_response")
        self.buttonGroup_figs = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_figs.setObjectName("buttonGroup_figs")
        self.buttonGroup_figs.addButton(self.fig_response)
        self.verticalLayout_10.addWidget(self.fig_response)
        self.fig_detrend = QtWidgets.QRadioButton(self.figures_box)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fig_detrend.setFont(font)
        self.fig_detrend.setStyleSheet("")
        self.fig_detrend.setObjectName("fig_detrend")
        self.buttonGroup_figs.addButton(self.fig_detrend)
        self.verticalLayout_10.addWidget(self.fig_detrend)
        self.groupBox = QtWidgets.QGroupBox(self.figures_box)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(-1, 1, -1, 1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_1 = QtWidgets.QGridLayout()
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.detrend_lowess = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.detrend_lowess.setFont(font)
        self.detrend_lowess.setIconSize(QtCore.QSize(12, 12))
        self.detrend_lowess.setObjectName("detrend_lowess")
        self.gridLayout_1.addWidget(self.detrend_lowess, 0, 1, 1, 1)
        self.detrend_linear = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.detrend_linear.setFont(font)
        self.detrend_linear.setIconSize(QtCore.QSize(12, 12))
        self.detrend_linear.setObjectName("detrend_linear")
        self.gridLayout_1.addWidget(self.detrend_linear, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_1)
        self.verticalLayout_10.addWidget(self.groupBox)
        self.line_2 = QtWidgets.QFrame(self.figures_box)
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_10.addWidget(self.line_2)
        self.fig_calibration = QtWidgets.QRadioButton(self.figures_box)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fig_calibration.setFont(font)
        self.fig_calibration.setObjectName("fig_calibration")
        self.buttonGroup_figs.addButton(self.fig_calibration)
        self.verticalLayout_10.addWidget(self.fig_calibration)
        self.comboBox_calcurve = QtWidgets.QComboBox(self.figures_box)
        self.comboBox_calcurve.setObjectName("comboBox_calcurve")
        self.verticalLayout_10.addWidget(self.comboBox_calcurve)
        self.checkBox_scale0 = QtWidgets.QCheckBox(self.figures_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_scale0.setFont(font)
        self.checkBox_scale0.setObjectName("checkBox_scale0")
        self.verticalLayout_10.addWidget(self.checkBox_scale0)
        self.checkBox_one2one = QtWidgets.QCheckBox(self.figures_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_one2one.setFont(font)
        self.checkBox_one2one.setObjectName("checkBox_one2one")
        self.verticalLayout_10.addWidget(self.checkBox_one2one)
        self.line_3 = QtWidgets.QFrame(self.figures_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_10.addWidget(self.line_3)
        self.fig_molefractions = QtWidgets.QRadioButton(self.figures_box)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fig_molefractions.setFont(font)
        self.fig_molefractions.setObjectName("fig_molefractions")
        self.buttonGroup_figs.addButton(self.fig_molefractions)
        self.verticalLayout_10.addWidget(self.fig_molefractions)
        self.layout_left.addWidget(self.figures_box)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_left.addItem(spacerItem)
        self.button_exportcsv = QtWidgets.QPushButton(self.tab)
        self.button_exportcsv.setObjectName("button_exportcsv")
        self.layout_left.addWidget(self.button_exportcsv)
        self.horizontalLayout_2.addLayout(self.layout_left)
        self.display_layout = QtWidgets.QVBoxLayout()
        self.display_layout.setObjectName("display_layout")
        self.mpl_plot = MplWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_plot.sizePolicy().hasHeightForWidth())
        self.mpl_plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.mpl_plot.setFont(font)
        self.mpl_plot.setObjectName("mpl_plot")
        self.display_layout.addWidget(self.mpl_plot)
        self.horizontalLayout_2.addLayout(self.display_layout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gases_box_2 = QtWidgets.QGroupBox(self.tab_2)
        self.gases_box_2.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(255, 253, 231);\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: left top;\n"
"    background: transparent;\n"
"}")
        self.gases_box_2.setObjectName("gases_box_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.gases_box_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.layout_gasbuttons_2 = QtWidgets.QGridLayout()
        self.layout_gasbuttons_2.setVerticalSpacing(10)
        self.layout_gasbuttons_2.setObjectName("layout_gasbuttons_2")
        self.button_CFC12_2 = QtWidgets.QRadioButton(self.gases_box_2)
        self.button_CFC12_2.setObjectName("button_CFC12_2")
        self.buttonGroup_mols2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_mols2.setObjectName("buttonGroup_mols2")
        self.buttonGroup_mols2.addButton(self.button_CFC12_2)
        self.layout_gasbuttons_2.addWidget(self.button_CFC12_2, 2, 1, 1, 1)
        self.button_CFC113_2 = QtWidgets.QRadioButton(self.gases_box_2)
        self.button_CFC113_2.setObjectName("button_CFC113_2")
        self.buttonGroup_mols2.addButton(self.button_CFC113_2)
        self.layout_gasbuttons_2.addWidget(self.button_CFC113_2, 1, 0, 1, 1)
        self.button_TCE_2 = QtWidgets.QRadioButton(self.gases_box_2)
        self.button_TCE_2.setObjectName("button_TCE_2")
        self.buttonGroup_mols2.addButton(self.button_TCE_2)
        self.layout_gasbuttons_2.addWidget(self.button_TCE_2, 5, 0, 1, 1)
        self.button_SF6_2 = QtWidgets.QRadioButton(self.gases_box_2)
        self.button_SF6_2.setObjectName("button_SF6_2")
        self.buttonGroup_mols2.addButton(self.button_SF6_2)
        self.layout_gasbuttons_2.addWidget(self.button_SF6_2, 1, 1, 1, 1)
        self.button_N2O_2 = QtWidgets.QRadioButton(self.gases_box_2)
        self.button_N2O_2.setObjectName("button_N2O_2")
        self.buttonGroup_mols2.addButton(self.button_N2O_2)
        self.layout_gasbuttons_2.addWidget(self.button_N2O_2, 0, 1, 1, 1)
        self.button_CHCl3_2 = QtWidgets.QRadioButton(self.gases_box_2)
        self.button_CHCl3_2.setObjectName("button_CHCl3_2")
        self.buttonGroup_mols2.addButton(self.button_CHCl3_2)
        self.layout_gasbuttons_2.addWidget(self.button_CHCl3_2, 2, 0, 1, 1)
        self.button_CFC11_2 = QtWidgets.QRadioButton(self.gases_box_2)
        self.button_CFC11_2.setEnabled(True)
        self.button_CFC11_2.setObjectName("button_CFC11_2")
        self.buttonGroup_mols2.addButton(self.button_CFC11_2)
        self.layout_gasbuttons_2.addWidget(self.button_CFC11_2, 0, 0, 1, 1)
        self.button_CCl4_2 = QtWidgets.QRadioButton(self.gases_box_2)
        self.button_CCl4_2.setObjectName("button_CCl4_2")
        self.buttonGroup_mols2.addButton(self.button_CCl4_2)
        self.layout_gasbuttons_2.addWidget(self.button_CCl4_2, 4, 0, 1, 1)
        self.button_MC_2 = QtWidgets.QRadioButton(self.gases_box_2)
        self.button_MC_2.setObjectName("button_MC_2")
        self.buttonGroup_mols2.addButton(self.button_MC_2)
        self.layout_gasbuttons_2.addWidget(self.button_MC_2, 3, 0, 1, 1)
        self.button_h1211_2 = QtWidgets.QRadioButton(self.gases_box_2)
        self.button_h1211_2.setObjectName("button_h1211_2")
        self.buttonGroup_mols2.addButton(self.button_h1211_2)
        self.layout_gasbuttons_2.addWidget(self.button_h1211_2, 3, 1, 1, 1)
        self.button_CFC11b_2 = QtWidgets.QRadioButton(self.gases_box_2)
        self.button_CFC11b_2.setObjectName("button_CFC11b_2")
        self.buttonGroup_mols2.addButton(self.button_CFC11b_2)
        self.layout_gasbuttons_2.addWidget(self.button_CFC11b_2, 4, 1, 1, 1)
        self.button_CFC113b_2 = QtWidgets.QRadioButton(self.gases_box_2)
        self.button_CFC113b_2.setObjectName("button_CFC113b_2")
        self.buttonGroup_mols2.addButton(self.button_CFC113b_2)
        self.layout_gasbuttons_2.addWidget(self.button_CFC113b_2, 5, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.layout_gasbuttons_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.gases_box_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.table_flasks = QtWidgets.QTableWidget(self.tab_2)
        self.table_flasks.setObjectName("table_flasks")
        self.table_flasks.setColumnCount(0)
        self.table_flasks.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.table_flasks)
        self.table_ports = QtWidgets.QTableWidget(self.tab_2)
        self.table_ports.setObjectName("table_ports")
        self.table_ports.setColumnCount(0)
        self.table_ports.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.table_ports)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setDefaultUp(True)
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDelete_Selected_Run = QtWidgets.QAction(MainWindow)
        self.actionDelete_Selected_Run.setObjectName("actionDelete_Selected_Run")
        self.actionExport_Selected_Run = QtWidgets.QAction(MainWindow)
        self.actionExport_Selected_Run.setObjectName("actionExport_Selected_Run")
        self.menuFiles.addAction(self.actionExport_Selected_Run)
        self.menuFiles.addSeparator()
        self.menuFiles.addAction(self.actionDelete_Selected_Run)
        self.menubar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FE3 Data Processing"))
        self.runselction_box.setTitle(_translate("MainWindow", "Run Selection"))
        self.label_runtype.setText(_translate("MainWindow", "Filter by run type"))
        self.label_rundate.setText(_translate("MainWindow", "Filter by run date"))
        self.gases_box.setTitle(_translate("MainWindow", "Gases"))
        self.button_CFC12.setText(_translate("MainWindow", "CFC-12"))
        self.button_CFC113.setText(_translate("MainWindow", "CFC-113"))
        self.button_TCE.setText(_translate("MainWindow", "TCE"))
        self.button_SF6.setText(_translate("MainWindow", "SF6"))
        self.button_N2O.setText(_translate("MainWindow", "N2O"))
        self.button_CHCl3.setText(_translate("MainWindow", "CHCl3"))
        self.button_CFC11.setText(_translate("MainWindow", "CFC-11"))
        self.button_CCl4.setText(_translate("MainWindow", "CCl4"))
        self.button_MC.setText(_translate("MainWindow", "MC"))
        self.button_h1211.setText(_translate("MainWindow", "h1211"))
        self.button_CFC11b.setText(_translate("MainWindow", "CFC-11 (b)"))
        self.button_CFC113b.setText(_translate("MainWindow", "CFC-113 (b)"))
        self.figures_box.setTitle(_translate("MainWindow", "Figure Selection"))
        self.fig_response.setText(_translate("MainWindow", "Response"))
        self.fig_detrend.setText(_translate("MainWindow", "Detrend"))
        self.detrend_lowess.setText(_translate("MainWindow", "Lowess"))
        self.detrend_linear.setText(_translate("MainWindow", "Point-to-point"))
        self.fig_calibration.setText(_translate("MainWindow", "Calibration curve"))
        self.checkBox_scale0.setText(_translate("MainWindow", "Scale to zero"))
        self.checkBox_one2one.setText(_translate("MainWindow", "One-to-One line"))
        self.fig_molefractions.setText(_translate("MainWindow", "Mole fractions"))
        self.button_exportcsv.setText(_translate("MainWindow", "Export run results to .csv"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Data View"))
        self.gases_box_2.setTitle(_translate("MainWindow", "FE3 Gases"))
        self.button_CFC12_2.setText(_translate("MainWindow", "CFC-12"))
        self.button_CFC113_2.setText(_translate("MainWindow", "CFC-113"))
        self.button_TCE_2.setText(_translate("MainWindow", "TCE"))
        self.button_SF6_2.setText(_translate("MainWindow", "SF6"))
        self.button_N2O_2.setText(_translate("MainWindow", "N2O"))
        self.button_CHCl3_2.setText(_translate("MainWindow", "CHCl3"))
        self.button_CFC11_2.setText(_translate("MainWindow", "CFC-11"))
        self.button_CCl4_2.setText(_translate("MainWindow", "CCl4"))
        self.button_MC_2.setText(_translate("MainWindow", "MC"))
        self.button_h1211_2.setText(_translate("MainWindow", "h1211"))
        self.button_CFC11b_2.setText(_translate("MainWindow", "CFC-11 (b)"))
        self.button_CFC113b_2.setText(_translate("MainWindow", "CFC-113 (b)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Ports and Flasks"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.actionDelete_Selected_Run.setText(_translate("MainWindow", "Delete Selected Run"))
        self.actionExport_Selected_Run.setText(_translate("MainWindow", "Export Selected Run"))

from mplwidget import MplWidget
